// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// StreamEvents: Kênh truyền 2 chiều (Bidirectional Streaming)
	// - Agent liên tục gửi Sysmon/Event Log lên Server (stream EventRequest)
	// - Server có thể đẩy lệnh Active Response xuống Agent bất kỳ lúc nào
	//   (stream CommandResponse) - ví dụ: KILL_PROCESS, BLOCK_IP
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (AgentService_StreamEventsClient, error)
	// Heartbeat: Agent gửi tín hiệu "còn sống" định kỳ (mỗi 30 giây)
	// Server cập nhật trạng thái online/offline trong Redis + PostgreSQL
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (AgentService_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], "/agent.AgentService/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceStreamEventsClient{stream}
	return x, nil
}

type AgentService_StreamEventsClient interface {
	Send(*EventRequest) error
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type agentServiceStreamEventsClient struct {
	grpc.ClientStream
}

func (x *agentServiceStreamEventsClient) Send(m *EventRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceStreamEventsClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/agent.AgentService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// StreamEvents: Kênh truyền 2 chiều (Bidirectional Streaming)
	// - Agent liên tục gửi Sysmon/Event Log lên Server (stream EventRequest)
	// - Server có thể đẩy lệnh Active Response xuống Agent bất kỳ lúc nào
	//   (stream CommandResponse) - ví dụ: KILL_PROCESS, BLOCK_IP
	StreamEvents(AgentService_StreamEventsServer) error
	// Heartbeat: Agent gửi tín hiệu "còn sống" định kỳ (mỗi 30 giây)
	// Server cập nhật trạng thái online/offline trong Redis + PostgreSQL
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) StreamEvents(AgentService_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).StreamEvents(&agentServiceStreamEventsServer{stream})
}

type AgentService_StreamEventsServer interface {
	Send(*CommandResponse) error
	Recv() (*EventRequest, error)
	grpc.ServerStream
}

type agentServiceStreamEventsServer struct {
	grpc.ServerStream
}

func (x *agentServiceStreamEventsServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceStreamEventsServer) Recv() (*EventRequest, error) {
	m := new(EventRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.AgentService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _AgentService_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
