# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\"\xe8\x01\n\x0c\x45ventRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x10\n\x08hostname\x18\x03 \x01(\t\x12\x12\n\nip_address\x18\x04 \x01(\t\x12\x13\n\x0braw_payload\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x33\n\x08metadata\x18\x07 \x03(\x0b\x32!.agent.EventRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xe1\x01\n\x0f\x43ommandResponse\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12(\n\x0c\x63ommand_type\x18\x02 \x01(\x0e\x32\x12.agent.CommandType\x12\x0e\n\x06target\x18\x03 \x01(\t\x12:\n\nparameters\x18\x04 \x03(\x0b\x32&.agent.CommandResponse.ParametersEntry\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xae\x01\n\x10HeartbeatRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x12\n\nip_address\x18\x03 \x01(\t\x12\x0f\n\x07os_type\x18\x04 \x01(\t\x12\x15\n\ragent_version\x18\x05 \x01(\t\x12\x11\n\tcpu_usage\x18\x06 \x01(\x01\x12\x14\n\x0cmemory_usage\x18\x07 \x01(\x01\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\"^\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\"\n\x1aheartbeat_interval_seconds\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t*\x8e\x01\n\x0b\x43ommandType\x12\x10\n\x0c\x43OMMAND_NONE\x10\x00\x12\x10\n\x0cKILL_PROCESS\x10\x01\x12\x0c\n\x08\x42LOCK_IP\x10\x02\x12\r\n\tBLOCK_URL\x10\x03\x12\x13\n\x0fQUARANTINE_FILE\x10\x04\x12\x14\n\x10\x43OLLECT_FORENSIC\x10\x05\x12\x13\n\x0fISOLATE_NETWORK\x10\x06\x32\x8f\x01\n\x0c\x41gentService\x12?\n\x0cStreamEvents\x12\x13.agent.EventRequest\x1a\x16.agent.CommandResponse(\x01\x30\x01\x12>\n\tHeartbeat\x12\x17.agent.HeartbeatRequest\x1a\x18.agent.HeartbeatResponseB%Z#soc-server/internal/generated/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#soc-server/internal/generated/proto'
  _globals['_EVENTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_EVENTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDRESPONSE_PARAMETERSENTRY']._loaded_options = None
  _globals['_COMMANDRESPONSE_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDTYPE']._serialized_start=759
  _globals['_COMMANDTYPE']._serialized_end=901
  _globals['_EVENTREQUEST']._serialized_start=23
  _globals['_EVENTREQUEST']._serialized_end=255
  _globals['_EVENTREQUEST_METADATAENTRY']._serialized_start=208
  _globals['_EVENTREQUEST_METADATAENTRY']._serialized_end=255
  _globals['_COMMANDRESPONSE']._serialized_start=258
  _globals['_COMMANDRESPONSE']._serialized_end=483
  _globals['_COMMANDRESPONSE_PARAMETERSENTRY']._serialized_start=434
  _globals['_COMMANDRESPONSE_PARAMETERSENTRY']._serialized_end=483
  _globals['_HEARTBEATREQUEST']._serialized_start=486
  _globals['_HEARTBEATREQUEST']._serialized_end=660
  _globals['_HEARTBEATRESPONSE']._serialized_start=662
  _globals['_HEARTBEATRESPONSE']._serialized_end=756
  _globals['_AGENTSERVICE']._serialized_start=904
  _globals['_AGENTSERVICE']._serialized_end=1047
# @@protoc_insertion_point(module_scope)
